const employees = [
  {
    id: 'goat1',
    name:'billy',
    disposition: 'rude',
    imageUrl: 'https://mm.aiircdn.com/3/5b8d51419125f.png',
    fullness: 67,
    favPose: 'warrior',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat2',
    name:'billy',
    disposition: 'rude',
    imageUrl: 'https://mm.aiircdn.com/3/5b8d51419125f.png',
    fullness: 67,
    favPose: 'warrior',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name:'barney',
    disposition: 'pugnacious',
    imageUrl: 'https://mm.aiircdn.com/3/5b8d51419125f.png',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name:'gruff',
    disposition: 'lazy',
    imageUrl: 'https://mm.aiircdn.com/3/5b8d51419125f.png',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: false,
    color: 'white',
  },
  {
    id: 'goat5',
    name:'belinda',
    disposition: 'rude',
    imageUrl: 'https://mm.aiircdn.com/3/5b8d51419125f.png',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
]

export default employees;